# Generated by Django 4.2.4 on 2023-10-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleManage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='user',
        ),
    ]
