# Generated by Django 4.2.4 on 2023-10-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleManage', '0003_categorie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
