# Generated by Django 4.2.4 on 2023-10-11 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArticleManage', '0004_userresponse_dislikes_userresponse_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='likes',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='dislikes',
            field=models.ManyToManyField(related_name='disliked_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='likes',
            field=models.ManyToManyField(related_name='liked_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
